name: Deploy-ubuntu

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Backend
        id: docker_build_backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ivan556/myoy-frontend

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: moyo.website
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_PRYVATE_KEY }}
          script: |
                  cd ~/staging && docker-compose pull &&\
                  make staging_up_and_build_one_service service=front
                 
